### ISSUE TITLE
Duplicate github actions

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/ianalyzer-readers#24]
Our current [test workflow](https://github.com/UUDigitalHumanitieslab/ianalyzer-readers/blob/develop/.github/workflows/python-package.yml) is trigged by pushes to certain branches, *and* by pull requests. But if you make a `feature/*` branch and then open a PR, that means the tests are run twice, which isn't necessary.

I think we can adjust the triggers like this and it should work as intended:

```
  push:
    branches: [ "develop", "main"]
  pull_request:
    branches: [ "develop" , "main"]
```
